### PR TITLE
Moved rule 14 example to rule 13 and replaced rule 14 with better example

### LINKED ISSUE #24: Rule 14: does double export make sense?
in the section: 
Rule-14: Use a single module.exports at the end of the Page Object file

in the example you make 2 exports.
But does such code example make any sense?

### PR DESCRIPTION
**Pull request by robinj**
Fixes #24 and #25

### CODE REVIEW

**Comment by robinj** [comment]
This change to the examples means that we can preserve the numbering of the rules but I am still not 100% sure on what to do with the explanations of rule 13 and 14.

**Comment by yadimon** [comment]
rule 13 still has double export, that is still wrong code. Should be (bad but) real example to avoid.

**Comment by robinj** [comment]
@yadimon I think you may have misunderstood the example. The "recommended" has two exports but they are in separate files. If you have any suggestions to make it clearer, I am happy to change it: 

  ```javascript
  /* recommended */

  /* user-profile.pageObject.js */
  var UserProfilePage = function() {};
  module.exports = UserProfilePage;

  /* user-settings.pageObject.js */
  var UserSettingsPage = function() {};
  module.exports = UserSettingsPage;
```

**Comment by yadimon** [comment]
@robinj by rule 13, the avoid example is not realistic, because of double export.
```
  /* avoid */

  /* user-profile.page.js */
  var UserProfilePage = function() {};
  var UserSettingsPage = function() {};

  module.exports = UserProfilePage;
  module.exports = UserSettingsPage;
```

**Comment by robinj** [comment]
Ahh yes, I see what you mean. I think I have an idea of how to fix it. I
will edit the example some time tomorrow.


On Tue, 31 Jan 2017, at 22:59, Dmitry Gorelenkov wrote:

> @robinj[1] by rule 13, the avoid example is not realistic, because of
> double export.


>   /* avoid */  /* user-profile.page.js */ var UserProfilePage =
>   function() {}; var UserSettingsPage = function() {};  module.exports
>   = UserProfilePage; module.exports = UserSettingsPage;
>
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 


Links:

  1. https://github.com/robinj
  2. https://github.com/CarmenPopoviciu/protractor-styleguide/pull/28#issuecomment-276521197

**Comment by robinj** [comment]
This should also fix #25

**Review by alecxe — COMMENTED** [review]
I would probably elaborate a bit more on the "Why?" but LGTM overall. Thanks!

**Pull request merged**
